{{- if .Values.csiProvider.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "secretsd.fullname" . }}-csi-provider
spec:
  selector:
    matchLabels: { app.kubernetes.io/name: {{ include "secretsd.name" . }}-csi }
  template:
    metadata:
      labels: { app.kubernetes.io/name: {{ include "secretsd.name" . }}-csi }
    spec:
      serviceAccountName: {{ default (include "secretsd.fullname" .) .Values.serviceAccount.name }}
      containers:
      - name: provider
        image: {{ .Values.csiProvider.image | quote }}
        env:
        - name: SECRETSD_URL
          value: "http://{{ include "secretsd.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local"
        {{- range $k, $v := .Values.csiProvider.env }}
        - name: {{ $k }}
          value: {{ $v | quote }}
        {{- end }}
{{- end }}
