{{- if .Values.eso.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ include "secretsd.fullname" . }}
spec:
  provider:
    webhook:
      url: "http://{{ include "secretsd.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local/v1/get?key={{`{{ .remoteRef.key }}`}}"
      result: { jsonPath: "$.value" }
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "secretsd.fullname" . }}-example
spec:
  refreshInterval: 2m
  secretStoreRef:
    name: {{ include "secretsd.fullname" . }}
    kind: SecretStore
  target: { name: example-db }
  data:
  - secretKey: DB_PASSWORD
    remoteRef: { key: db/password }
{{- end }}
