FROM golang:1.25-alpine AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /out/secretsd ./cmd/secretsd

FROM gcr.io/distroless/base-debian12
COPY --from=build /out/secretsd /secretsd
EXPOSE 8080
USER nonroot:nonroot
ENTRYPOINT ["/secretsd"]
