name: ci
on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_OWNER: ${{ github.repository_owner }}
  CHART_DIR: charts/secretsd

jobs:
  lint-chart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4
        with: { version: v3.15.2 }
      - run: helm lint "$CHART_DIR"

  build-and-push:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Compute tags
        id: vars
        shell: bash
        run: |
          OWNER_LC=$(echo "${{ env.IMAGE_OWNER }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_BASE_GHCR=${{ env.REGISTRY }}/${OWNER_LC}
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            VER=${GITHUB_REF_NAME}
          else
            SHORT_SHA=$(git rev-parse --short HEAD)
            VER="sha-${SHORT_SHA}"
          fi
          echo "image_base_ghcr=${IMAGE_BASE_GHCR}" >> $GITHUB_OUTPUT
          echo "tag=${VER}" >> $GITHUB_OUTPUT
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.secretsd
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ steps.vars.outputs.image_base_ghcr }}/secretsd:${{ steps.vars.outputs.tag }}
            ${{ steps.vars.outputs.image_base_ghcr }}/secretsd:latest
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.csi-provider
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ steps.vars.outputs.image_base_ghcr }}/csi-provider:${{ steps.vars.outputs.tag }}
            ${{ steps.vars.outputs.image_base_ghcr }}/csi-provider:latest
